//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BogorSehat.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antrian
    {
        public int id { get; set; }
        public string NIK { get; set; }
        public int NoAntrian { get; set; }
        public System.DateTime TanggalDaftar { get; set; }
        public string IdLayananRS { get; set; }
    
        public virtual LayananR LayananR { get; set; }
        public virtual Pasien Pasien { get; set; }
    }
}
