//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BogorSehat.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class JadwalLayanan
    {
        public int IdJadwal { get; set; }
        public string IdLayananRS { get; set; }
        public string IdDokter { get; set; }
        public string Hari { get; set; }
        public System.TimeSpan JamMulai { get; set; }
        public System.TimeSpan JamSelesai { get; set; }
    
        public virtual Dokter Dokter { get; set; }
        public virtual LayananR LayananR { get; set; }
    }
}
