//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BogorSehat.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konsultasi
    {
        public string NIK { get; set; }
        public string NPA { get; set; }
        public string Chat { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Dokter Dokter { get; set; }
        public virtual Pasien Pasien { get; set; }
    }
}
