//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadExcelBogorSehat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dokter()
        {
            this.Konsultasis = new HashSet<Konsultasi>();
            this.JadwalLayanans = new HashSet<JadwalLayanan>();
        }
    
        public string NPA { get; set; }
        public string Nama { get; set; }
        public string JenisKelamin { get; set; }
        public Nullable<System.DateTime> TanggalLahir { get; set; }
        public string KotaLahir { get; set; }
        public string Email { get; set; }
        public string Alamat { get; set; }
        public string Password { get; set; }
        public string IdSpesialis { get; set; }
        public Nullable<int> Agama { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual Agama Agama1 { get; set; }
        public virtual Spesiali Spesiali { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Konsultasi> Konsultasis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JadwalLayanan> JadwalLayanans { get; set; }
    }
}
