//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadExcelBogorSehat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LayananR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LayananR()
        {
            this.JadwalLayanans = new HashSet<JadwalLayanan>();
        }
    
        public string IdLayanan { get; set; }
        public string IdRS { get; set; }
        public string IdLayananRS { get; set; }
    
        public virtual JenisLayanan JenisLayanan { get; set; }
        public virtual RumahSakit RumahSakit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JadwalLayanan> JadwalLayanans { get; set; }
    }
}
