//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadExcelBogorSehat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spesiali
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spesiali()
        {
            this.Dokters = new HashSet<Dokter>();
        }
    
        public string IdSpesialis { get; set; }
        public string NamaSpesialis { get; set; }
        public string Gelar { get; set; }
        public string Deskripsi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dokter> Dokters { get; set; }
    }
}
