using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BogorHealth.Models.Data
{
    [Table("User")]
    public class User
    {
        public User()
        {

        }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]//switch on autogenerated
        public int Id { get; set; }
        [Key]//set as Primary key
        public string NIK { get; set; }
        [Required]
        public string Username { get; set; }
        [Required]
        public string Password { get; set; }
        public DateTime Date_Register { get; set; }
        public int isActive { get; set; }
    }
}